source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include? '/'
  "https://github.com/#{repo_name}.git"
end

ruby '>= 3.0.0'

gem 'bcrypt'
gem 'puma', '~> 5.6'
gem 'rack-cors', require: 'rack/cors'
gem 'rails', '~> 7.0.0'
gem 'sqlite3', '~> 1.4'
gem 'validate_url'

gem 'graphql'
gem 'graphql-query-resolver'
gem 'search_object'
gem 'search_object_graphql'

group :development, :test do
  gem 'byebug', platforms: %i(mri mingw x64_mingw)
  gem 'factory_bot_rails', '>= 6.5.1'
  gem 'graphiql-rails', '~> 1.8'
  gem 'rubocop'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end
